# Generated by Django 5.1.7 on 2025-04-04 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ganaderos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ganado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(max_length=100, unique=True)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('peso', models.FloatField()),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.ganaderos')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='gestion.ganaderos')),
                ('ganado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.ganado')),
            ],
        ),
        migrations.CreateModel(
            name='Traspaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('dueño_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_destino', to='gestion.ganaderos')),
                ('dueño_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_origen', to='gestion.ganaderos')),
                ('ganado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.ganado')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprador', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ganado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.ganado')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='gestion.ganaderos')),
            ],
        ),
    ]
